spring.application.name=notification-service

server.port=8084

# ==============================
# PostgreSQL
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==============================
# Flyway
# ==============================
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

# ==============================
# Eureka
# ==============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

#############################################
# Kafka
#############################################

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-group

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.apexbank.common.dto

#############################################
# Mail
#############################################

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# ==============================
# Actuator
# ==============================
management.endpoints.web.exposure.include=health,info

# ==============================
# Swagger
# ==============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html