spring.application.name=transaction-service

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/transaction_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

#################################################
# Resilience4j Circuit Breaker
#################################################

resilience4j.circuitbreaker.instances.accountService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.accountService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.accountService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.accountService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.accountService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.accountService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.accountService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.accountService.automaticTransitionFromOpenToHalfOpenEnabled=true

#################################################
# Eureka
#################################################

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

#################################################
# Retry
#################################################

resilience4j.retry.instances.accountService.maxAttempts=3
resilience4j.retry.instances.accountService.waitDuration=2s

#################################################
# Time Limiter
#################################################

resilience4j.timelimiter.instances.accountService.timeoutDuration=5s