spring.application.name=api-gateway
server.port=9000

# Gateway Route
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

# Actuator
management.endpoints.web.exposure.include=health,info

# Keycloak Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/apex-bank